SELECT * FROM EMP;

SELECT DISTINCT JOB
FROM EMP;

SELECT EMPNO AS EMPLOYEE_NO,
ENAME AS EMPLOYEE_NAME,
JOB,
MGR AS MANAGER,
HIREDATE,
SAL AS SALARY,
COMM AS COMMISSION,
DEPTNO AS DEPARTMENT_NO
FROM EMP;

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL <= 1500;

SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND SAL NOT BETWEEN 1000 AND 2000;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30 AND JOB LIKE 'SALESMAN';

SELECT LPAD('ORACLE',10,'#') AS LPAD1,
RPAD('ORACLE',10,'*') AS RPAD2
FROM DUAL;

SELECT MOD(15,0) AS MOD1 FROM DUAL;